#coding: utf-8
from datetime import date

import boundaries

boundaries.register(u'Ahuntsic-Cartierville districts',
    domain=u'Ahuntsic-Cartierville, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Anjou districts',
    domain=u'Anjou, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Côte-des-Neiges—Notre-Dame-de-Grâce districts',
    domain=u'Côte-des-Neiges—Notre-Dame-de-Grâce, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Lachine districts',
    domain=u'Lachine, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'LaSalle districts',
    domain=u'LaSalle, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Le Sud-Ouest districts',
    domain=u'Le Sud-Ouest, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'L\'Île-Bizard—Sainte-Geneviève districts',
    domain=u'L\'Île-Bizard—Sainte-Geneviève, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Mercier—Hochelaga-Maisonneuve districts',
    domain=u'Mercier—Hochelaga-Maisonneuve, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Montréal-Nord districts',
    domain=u'Montréal-Nord, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Outremont districts',
    domain=u'Outremont, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Pierrefonds-Roxboro districts',
    domain=u'Pierrefonds-Roxboro, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Le Plateau-Mont-Royal districts',
    domain=u'Le Plateau-Mont-Royal, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Rivière-des-Prairies—Pointe-aux-Trembles districts',
    domain=u'Rivière-des-Prairies—Pointe-aux-Trembles, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Rosemont—La Petite-Patrie districts',
    domain=u'Rosemont—La Petite-Patrie, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Saint-Laurent districts',
    domain=u'Saint-Laurent, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Saint-Léonard districts',
    domain=u'Saint-Leonard, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Verdun districts',
    domain=u'Verdun, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Ville-Marie districts',
    domain=u'Ville-Marie, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)

boundaries.register(u'Villeray—Saint-Michel—Parc-Extension districts',
    domain=u'Villeray—Saint-Michel—Parc-Extension, Montréal, QC',
    last_updated=date(2013, 4, 2),
    name_func=boundaries.clean_attr('NOM_DISTRI'),
    authority=u'Ville de Montréal',
    source_url='http://donnees.ville.montreal.qc.ca/fiche/polygones-arrondissements/',
    licence_url='http://donnees.ville.montreal.qc.ca/licence/licence-texte-complet/',
    data_url='http://donnees.ville.montreal.qc.ca/fiche/elections-2009-districts/data.zip',
    notes='District extracted from original shapefile',
    encoding='iso-8859-1',
)
